language: node_js
sudo: false
services:
  - redis-server
node_js:
  - "9"
  - "8"
  - "7"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "9"
    - node_js: "7"
